"""Idempotent seed script — safe to run multiple times.

All 30 records use fixed UUIDs so re-runs produce identical inserts.
Complaints reflect Pakistani municipal context as required.

Usage:
    cd backend
    python -m scripts.seed
"""
import asyncio
import uuid
from sqlalchemy import select
from app.core.database import AsyncSessionLocal
from app.models import Complaint, Category, Priority, ComplaintStatus

# ---------------------------------------------------------------------------
# Seed data — 30 complaints with fixed UUIDs for strict idempotency
# ---------------------------------------------------------------------------
SEED_DATA: list[dict] = [
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000001"),
        "text": "The nullah is choked and sewage is spilling over onto the main road since last night.",
        "location": "Sector F-6/1, Islamabad",
        "reporter_contact": "0300-1234567",
        "category": Category.sanitation,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Nullah overflow causing sewage spill onto road",
        "triaged_by": "rules",
        "triage_latency_ms": 120,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000002"),
        "text": "No electricity since sehri, WAPDA helpline is not responding at all.",
        "location": "Gulberg III, Lahore",
        "reporter_contact": "0321-9876543",
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Power outage since early morning, helpline unresponsive",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 340,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000003"),
        "text": "Water main has been leaking since fajr, the entire street is flooded.",
        "location": "Clifton Block 5, Karachi",
        "reporter_contact": "0333-1122334",
        "category": Category.water,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Water pipeline burst flooding entire street since dawn",
        "triaged_by": "llm:gemini",
        "triage_latency_ms": 450,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000004"),
        "text": "Transformer burst with a loud bang and sparks are flying, very dangerous situation.",
        "location": "Johar Town, Lahore",
        "reporter_contact": None,
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.resolved,
        "ai_summary": "Transformer explosion with sparks — dangerous situation",
        "triaged_by": "llm:ollama",
        "triage_latency_ms": 800,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000005"),
        "text": "Sewerage is bubbling from the manhole cover near the central mosque.",
        "location": "DHA Phase 2, Islamabad",
        "reporter_contact": "0345-9988776",
        "category": Category.sanitation,
        "priority": Priority.normal,
        "status": ComplaintStatus.open,
        "ai_summary": "Sewerage overflow from manhole near mosque",
        "triaged_by": "rules",
        "triage_latency_ms": 110,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000006"),
        "text": "Large potholes on the main University Road are causing daily accidents to motorcyclists.",
        "location": "University Road, Peshawar",
        "reporter_contact": "0311-2233445",
        "category": Category.roads,
        "priority": Priority.normal,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Dangerous potholes on University Road causing accidents",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 320,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000007"),
        "text": "All streetlights on our block have been dead for the last two weeks, very unsafe at night.",
        "location": "Satellite Town, Rawalpindi",
        "reporter_contact": None,
        "category": Category.streetlights,
        "priority": Priority.low,
        "status": ComplaintStatus.open,
        "ai_summary": "Streetlights non-functional for two weeks causing safety hazard",
        "triaged_by": "rules:fallback",
        "triage_latency_ms": 50,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000008"),
        "text": "Garbage dump near the community park is burning and causing severe smoke inhalation.",
        "location": "Korangi, Karachi",
        "reporter_contact": "0300-5556667",
        "category": Category.other,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Burning garbage causing severe air pollution",
        "triaged_by": "llm:gemini",
        "triage_latency_ms": 550,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000009"),
        "text": "Load-shedding has exceeded 12 hours a day for the past week, businesses are shutting down.",
        "location": "Liaquat Abad, Karachi",
        "reporter_contact": "0301-7654321",
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "12-hour load-shedding destroying local businesses",
        "triaged_by": "simulated",
        "triage_latency_ms": 75,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000010"),
        "text": "Bijli ka khamba is tilted dangerously over the school gate, children are at risk.",
        "location": "G-9/2, Islamabad",
        "reporter_contact": "0322-5544332",
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Tilted electricity pole endangering school children",
        "triaged_by": "rules",
        "triage_latency_ms": 95,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000011"),
        "text": "Pani band hai teen din se, tanker bhi nahi aa raha, please koi sunay.",
        "location": "Orangi Town, Karachi",
        "reporter_contact": "0300-9988001",
        "category": Category.water,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "No water supply for three days, tanker also unavailable",
        "triaged_by": "rules",
        "triage_latency_ms": 88,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000012"),
        "text": "Sadak toot chuki hai, baarish ke baad gaddhe itne bade hogaye ke gaari phans jaati hai.",
        "location": "Model Town, Lahore",
        "reporter_contact": None,
        "category": Category.roads,
        "priority": Priority.normal,
        "status": ComplaintStatus.rejected,
        "ai_summary": "Road badly damaged, vehicles getting stuck in potholes",
        "triaged_by": "rules",
        "triage_latency_ms": 102,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000013"),
        "text": "Street drain overflowing due to clogged pipes after last night's rainfall.",
        "location": "Bahria Town Phase 4, Rawalpindi",
        "reporter_contact": "0315-6677889",
        "category": Category.sanitation,
        "priority": Priority.normal,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Clogged drain causing street flooding after rainfall",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 380,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000014"),
        "text": "The overhead water tank for our building has not been cleaned in over six months.",
        "location": "Nazimabad Block 3, Karachi",
        "reporter_contact": "0333-4455667",
        "category": Category.water,
        "priority": Priority.normal,
        "status": ComplaintStatus.open,
        "ai_summary": "Water tank not cleaned for 6 months — health hazard",
        "triaged_by": "simulated",
        "triage_latency_ms": 62,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000015"),
        "text": "High tension wire has snapped and is hanging loose over the pedestrian footpath.",
        "location": "Cantt, Lahore",
        "reporter_contact": "0300-1011121",
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Snapped high-tension wire over pedestrian footpath",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 290,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000016"),
        "text": "Two streetlights near the graveyard are not working, residents are scared to walk at night.",
        "location": "Gulshan-e-Iqbal, Karachi",
        "reporter_contact": None,
        "category": Category.streetlights,
        "priority": Priority.low,
        "status": ComplaintStatus.resolved,
        "ai_summary": "Non-functional streetlights near graveyard causing fear",
        "triaged_by": "rules:fallback",
        "triage_latency_ms": 55,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000017"),
        "text": "Garbage has not been collected for ten days, the smell is unbearable for residents.",
        "location": "Hayatabad Phase 5, Peshawar",
        "reporter_contact": "0344-3322110",
        "category": Category.sanitation,
        "priority": Priority.normal,
        "status": ComplaintStatus.open,
        "ai_summary": "Garbage collection skipped for 10 days causing stench",
        "triaged_by": "rules",
        "triage_latency_ms": 98,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000018"),
        "text": "Main water supply pipe burst underground, creating a sinkhole in the middle of the road.",
        "location": "F-10 Markaz, Islamabad",
        "reporter_contact": "0321-1234560",
        "category": Category.water,
        "priority": Priority.high,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Underground pipe burst creating dangerous road sinkhole",
        "triaged_by": "llm:gemini",
        "triage_latency_ms": 520,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000019"),
        "text": "Bridge over the seasonal stream has severe cracks and shakes when heavy trucks pass.",
        "location": "Saddar, Quetta",
        "reporter_contact": "0311-9900112",
        "category": Category.roads,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Cracked bridge dangerous for heavy vehicles",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 410,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000020"),
        "text": "Load-shedding during exam season is destroying students' study schedules every night.",
        "location": "Wah Cantt, Punjab",
        "reporter_contact": "0300-7788990",
        "category": Category.electricity,
        "priority": Priority.normal,
        "status": ComplaintStatus.open,
        "ai_summary": "Load-shedding disrupting student exam preparation",
        "triaged_by": "simulated",
        "triage_latency_ms": 71,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000021"),
        "text": "Raw sewage from broken drains is mixing directly into the local drinking water supply.",
        "location": "Larkana, Sindh",
        "reporter_contact": "0333-8899001",
        "category": Category.sanitation,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Sewage contaminating drinking water supply — public health emergency",
        "triaged_by": "llm:ollama",
        "triage_latency_ms": 690,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000022"),
        "text": "Speed breakers on school road are completely invisible at night due to no markings.",
        "location": "DHA Phase 6, Lahore",
        "reporter_contact": None,
        "category": Category.roads,
        "priority": Priority.low,
        "status": ComplaintStatus.open,
        "ai_summary": "Unmarked speed breakers on school road causing night accidents",
        "triaged_by": "rules",
        "triage_latency_ms": 80,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000023"),
        "text": "Electric meter box on the ground floor is sparking and smells like burning rubber.",
        "location": "Gulberg II, Lahore",
        "reporter_contact": "0300-2233440",
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Sparking meter box with burning rubber smell — fire hazard",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 355,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000024"),
        "text": "Bijli gul hai aur inverter bhi kharab hogaya, raat ko andhere mein baith rahe hain.",
        "location": "Qasimabad, Hyderabad",
        "reporter_contact": "0322-4455667",
        "category": Category.electricity,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Complete darkness due to power cut and broken inverter",
        "triaged_by": "rules",
        "triage_latency_ms": 115,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000025"),
        "text": "Public toilet in the park has been locked for a month, residents have nowhere to go.",
        "location": "Jinnah Park, Rawalpindi",
        "reporter_contact": None,
        "category": Category.other,
        "priority": Priority.low,
        "status": ComplaintStatus.resolved,
        "ai_summary": "Park public toilet locked for a month — sanitation inconvenience",
        "triaged_by": "simulated",
        "triage_latency_ms": 68,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000026"),
        "text": "Nala overflow has destroyed the boundary wall of two houses in our street.",
        "location": "Samnabad, Lahore",
        "reporter_contact": "0315-5544221",
        "category": Category.sanitation,
        "priority": Priority.high,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Nala overflow damaged two boundary walls",
        "triaged_by": "llm:gemini",
        "triage_latency_ms": 490,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000027"),
        "text": "Water pressure is extremely low since the new housing scheme connected to our supply line.",
        "location": "G-11/4, Islamabad",
        "reporter_contact": "0300-9876001",
        "category": Category.water,
        "priority": Priority.normal,
        "status": ComplaintStatus.open,
        "ai_summary": "Low water pressure since new scheme tapped into supply",
        "triaged_by": "rules:fallback",
        "triage_latency_ms": 58,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000028"),
        "text": "Footpath tiles are broken and uplifted, elderly people keep tripping and falling.",
        "location": "Cantt, Peshawar",
        "reporter_contact": "0344-1199003",
        "category": Category.roads,
        "priority": Priority.normal,
        "status": ComplaintStatus.rejected,
        "ai_summary": "Broken footpath tiles causing elderly to trip and fall",
        "triaged_by": "rules",
        "triage_latency_ms": 92,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000029"),
        "text": "Streetlight pole has fallen across the road after last night's storm, traffic is blocked.",
        "location": "Gulshan-e-Ravi, Lahore",
        "reporter_contact": "0300-6677001",
        "category": Category.streetlights,
        "priority": Priority.high,
        "status": ComplaintStatus.in_progress,
        "ai_summary": "Fallen streetlight pole blocking road after storm",
        "triaged_by": "llm:groq",
        "triage_latency_ms": 300,
    },
    {
        "id": uuid.UUID("00000001-0000-0000-0000-000000000030"),
        "text": "Community water filtration plant has not been operational for 15 days, no clean water available.",
        "location": "Lyari, Karachi",
        "reporter_contact": "0333-0011223",
        "category": Category.water,
        "priority": Priority.high,
        "status": ComplaintStatus.open,
        "ai_summary": "Water filtration plant down for 15 days — no clean water",
        "triaged_by": "llm:gemini",
        "triage_latency_ms": 475,
    },
]


async def seed_data() -> None:
    """Insert seed records. Strictly idempotent: skips records with matching id."""
    async with AsyncSessionLocal() as session:
        inserted = 0
        skipped = 0
        for data in SEED_DATA:
            existing = await session.execute(
                select(Complaint).where(Complaint.id == data["id"])
            )
            if existing.scalars().first() is not None:
                skipped += 1
                continue
            complaint = Complaint(**data)
            session.add(complaint)
            inserted += 1
        await session.commit()
        print(
            f"Seed complete: {inserted} inserted, {skipped} skipped "
            f"(total records: {len(SEED_DATA)})"
        )


async def main() -> None:
    await seed_data()


if __name__ == "__main__":
    asyncio.run(main())
