apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/YOUR_ORG/civicpulse-backend
    newName: ghcr.io/o0on/civicpulse-backend
    newTag: local
  - name: ghcr.io/YOUR_ORG/civicpulse-frontend
    newName: ghcr.io/o0on/civicpulse-frontend
    newTag: local
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: HorizontalPodAutoscaler
      name: backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
